/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SystemAdmin;

import Business.Buyer.Buyer;
import Business.EcoSystem;
import Business.ExpressCompany.ExpressCompany;
import Business.Network.Network;
import Business.Seller.Seller;
import Business.Service.Service;
import Business.Supplier.Supplier;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author TT1
 */
     

    public class NetworkMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemMainJPanel
     */
   
        JPanel userProcessContainer;
        EcoSystem system;
        Network network;
    NetworkMainJPanel(JPanel userProcessContainer, EcoSystem system,Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.network=network;
        this.system=system;
        label.setText(network.getName());
        populateTree();
    }

   public void populateTree(){
        DefaultTreeModel model=(DefaultTreeModel)jTree1.getModel();
       // Add the code for draw your system structure shown by JTree
        ArrayList<Buyer> buyerList=network.getBuyerDirectory().getBuyerList();
        ArrayList<Seller> sellerList=network.getSellerDirectory().getSellerList();
        ArrayList<ExpressCompany> expressCompanyList=network.getExpressCompanyDir().getExpressCompanyList();
        ArrayList<Supplier> supplierList = network.getSupplierDirectory().getsupplierList();
        ArrayList<Service> serviceList = network.getServiceDir().getserviceList();
       
        DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        
        DefaultMutableTreeNode buy=new DefaultMutableTreeNode("Buyer");
        root.insert(buy, 0);        
        for(int i=0;i<buyerList.size();i++){
            Buyer buyer=buyerList.get(i);
            DefaultMutableTreeNode buyerNode=new DefaultMutableTreeNode(buyer);
            buy.insert(buyerNode, i);
        }          
        
        DefaultMutableTreeNode sell=new DefaultMutableTreeNode("Seller");
        root.insert(sell, 0);        
        for(int i=0;i<sellerList.size();i++){
            Seller seller=sellerList.get(i);
            DefaultMutableTreeNode sellerNode=new DefaultMutableTreeNode(seller);
            sell.insert(sellerNode, i);
        }
        
        DefaultMutableTreeNode express=new DefaultMutableTreeNode("ExpressCompany");      
        root.insert(express, 1);
        for(int i=0;i<expressCompanyList.size();i++){
            ExpressCompany expressCompany=expressCompanyList.get(i);
            DefaultMutableTreeNode expressCompanyNode=new DefaultMutableTreeNode(expressCompany);
            express.insert(expressCompanyNode, i);
        }
        
        DefaultMutableTreeNode sup=new DefaultMutableTreeNode("Supplier");      
        root.insert(sup, 1);
        for(int i=0;i<supplierList.size();i++){
            Supplier supplier=supplierList.get(i);
            DefaultMutableTreeNode supplierNode=new DefaultMutableTreeNode(supplier);
            sup.insert(supplierNode, i);
        }
        
        DefaultMutableTreeNode ser=new DefaultMutableTreeNode("Service");      
        root.insert(ser, 1);
        for(int i=0;i<serviceList.size();i++){
            Service service=serviceList.get(i);
            DefaultMutableTreeNode serviceNode=new DefaultMutableTreeNode(service.getUserAccount().getUsername());
            ser.insert(serviceNode, i);
        }
        
        model.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        btnManageSupplier = new javax.swing.JButton();
        btnManageDeliveryCompany = new javax.swing.JButton();
        btnManageSeller = new javax.swing.JButton();
        btnManageBuyer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        btnManageService = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(java.awt.Color.pink);

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 376, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(java.awt.Color.pink);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageSupplier.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnManageSupplier.setText("Manage supplier");
        btnManageSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSupplierActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 406, 324, 41));

        btnManageDeliveryCompany.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnManageDeliveryCompany.setText("Manage delivery company");
        btnManageDeliveryCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDeliveryCompanyActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageDeliveryCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 331, 324, 41));

        btnManageSeller.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnManageSeller.setText("Manage seller");
        btnManageSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSellerActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 259, 324, 41));

        btnManageBuyer.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnManageBuyer.setText("Manage buyer");
        btnManageBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBuyerActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 184, 324, 41));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Systemadmin Main Screen");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 34, -1, -1));

        label.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        label.setText("Network:");
        jPanel2.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 114, 119, -1));

        btnManageService.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnManageService.setText("Manage Customer Service Staff");
        btnManageService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageServiceActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageService, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 491, 324, 40));

        jLabel3.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel3.setText("Network:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 114, 119, -1));

        btnBack.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 492, 121, 38));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/003-地球.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 23, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/013-管理.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 549, -1, -1));

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBuyerActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout)userProcessContainer.getLayout();
               userProcessContainer.add(new ManageBuyerJPanel(userProcessContainer,system,network));
                layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageBuyerActionPerformed

    private void btnManageSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSellerActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout)userProcessContainer.getLayout();
               userProcessContainer.add(new ManageSellerJPanel(userProcessContainer,system,network));
                layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageSellerActionPerformed

    private void btnManageDeliveryCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDeliveryCompanyActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout)userProcessContainer.getLayout();
               userProcessContainer.add(new ManageDeliveryCompanyJPanel(userProcessContainer,system,network));
                layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDeliveryCompanyActionPerformed

    private void btnManageSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSupplierActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout)userProcessContainer.getLayout();
               userProcessContainer.add(new ManageSupplierJPanel(userProcessContainer,system,network));
                layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageSupplierActionPerformed

    private void btnManageServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageServiceActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout)userProcessContainer.getLayout();
               userProcessContainer.add(new ManageServiceJPanel(userProcessContainer,system,network));
                layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageServiceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
//          userProcessContainer.remove(this);
//        Component[] componentArray = userProcessContainer.getComponents();
//        Component component = componentArray[componentArray.length - 1];
//        SystemMainJPanel dwjp = (SystemMainJPanel) component;
//        dwjp.populateTable();
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
               userProcessContainer.add(new SystemMainJPanel(userProcessContainer,system));
                layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManageBuyer;
    private javax.swing.JButton btnManageDeliveryCompany;
    private javax.swing.JButton btnManageSeller;
    private javax.swing.JButton btnManageService;
    private javax.swing.JButton btnManageSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
