/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SystemAdmin;

import Business.EcoSystem;
import Business.Network.Network;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author TT1
 */
public class SystemMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemMainJPanel
     */
   JPanel userProcessContainer;
    EcoSystem system;
        
    

    public SystemMainJPanel(JPanel userProcessContainer, EcoSystem system) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
        this.system=system;
        populateTable();
        populateTree();
    }

    
    public void populateTable(){
        int rowCount = table.getRowCount();
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        for(Network network:system.getNetworkList()){
            
                Object row[] = new Object[1];
                row[0] = network;
                
                
                model.addRow(row);
                }
            }
    
    public void populateTree(){
        DefaultTreeModel model=(DefaultTreeModel)jTree1.getModel();
       // Add the code for draw your system structure shown by JTree
        ArrayList<Network> networkList = system.getNetworkList();
 
        DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        
        DefaultMutableTreeNode net=new DefaultMutableTreeNode("Networks");
        root.insert(net, 0);        
        for(int i=0;i<networkList.size();i++){
            Network network=networkList.get(i);
            DefaultMutableTreeNode networkNode=new DefaultMutableTreeNode(network);
            net.insert(networkNode, i);
        }
        model.reload();
    }
//    public void populateTree(){
//        DefaultTreeModel model=(DefaultTreeModel)jTree.getModel();
//       // Add the code for draw your system structure shown by JTree
//       ArrayList<Customer> customerList=ecosystem.getCustomerDirectory().getCustomerList();
//       ArrayList<DeliveryMan> deliveryList=ecosystem.getDeliveryManDirectory().getDeliveryManList();
//       ArrayList<Restaurant> restaurantList=ecosystem.getRestaurantDirectory().getRestaurantList();
//       
// 
//        DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
//        root.removeAllChildren();
//        
//        DefaultMutableTreeNode cus=new DefaultMutableTreeNode("Customers");
//        root.insert(cus, 0);        
//        for(int i=0;i<customerList.size();i++){
//            Customer customer=customerList.get(i);
//            DefaultMutableTreeNode customerNode=new DefaultMutableTreeNode(customer.getUserAccount().getUsername());
//            cus.insert(customerNode, i);
//          }
//          
//        
//        DefaultMutableTreeNode del=new DefaultMutableTreeNode("DeliveryMen");      
//        root.insert(del, 1);
//        for(int i=0;i<deliveryList.size();i++){
//            DeliveryMan delivery=deliveryList.get(i);
//            DefaultMutableTreeNode deliveryNode=new DefaultMutableTreeNode(delivery.getUserAccount().getUsername());
//            del.insert(deliveryNode, i);
//          }
//          
//       DefaultMutableTreeNode res=new DefaultMutableTreeNode("Restaursnts");
//        root.insert(res, 2); 
//        for(int i=0;i<restaurantList.size();i++){
//            Restaurant restaurant=restaurantList.get(i);
//            DefaultMutableTreeNode restaurantNode=new DefaultMutableTreeNode(restaurant.getUserAccount().getUsername());
//            res.insert(restaurantNode, i);
//          }
//        model.reload();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        btnEnterNetwork = new javax.swing.JButton();
        btnCreateNetwork = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtNetwork = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnChartReport = new javax.swing.JButton();

        jPanel1.setBackground(java.awt.Color.pink);

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 376, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(java.awt.Color.pink);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnterNetwork.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnEnterNetwork.setText("Enter Network");
        btnEnterNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterNetworkActionPerformed(evt);
            }
        });
        jPanel2.add(btnEnterNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 343, -1, 41));

        btnCreateNetwork.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnCreateNetwork.setText("Create Network");
        btnCreateNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNetworkActionPerformed(evt);
            }
        });
        jPanel2.add(btnCreateNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 343, -1, 41));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("System Admin Main Screen");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 36, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 108, 424, 147));
        jPanel2.add(txtNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 287, 169, -1));

        jLabel5.setText("Network:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 292, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/023-货物查询.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 402, 70, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/001-地球.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 33, -1, -1));

        btnChartReport.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnChartReport.setText("Chart Report");
        btnChartReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChartReportActionPerformed(evt);
            }
        });
        jPanel2.add(btnChartReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 160, 41));

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNetworkActionPerformed
        // TODO add your handling code here:
        system.createAndAddNetwork(txtNetwork.getText());
        populateTable();
        txtNetwork.setText("");
    }//GEN-LAST:event_btnCreateNetworkActionPerformed

    private void btnEnterNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterNetworkActionPerformed
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Network network = (Network)table.getValueAt(selectedRow, 0);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
               userProcessContainer.add(new NetworkMainJPanel(userProcessContainer,system,network));
                layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEnterNetworkActionPerformed

    private void btnChartReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChartReportActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
               userProcessContainer.add(new ChartJPanel(userProcessContainer,system));
                layout.next(userProcessContainer);
    }//GEN-LAST:event_btnChartReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChartReport;
    private javax.swing.JButton btnCreateNetwork;
    private javax.swing.JButton btnEnterNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtNetwork;
    // End of variables declaration//GEN-END:variables
}
