/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Seller;

import Business.Network.Network;
import Business.Seller.Seller;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author TT1
 */
public class ManageSellerInformationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSellerInformationJPanel
     */
    JPanel userProcessContainer;
    Network network;
    Seller seller;
        
    public ManageSellerInformationJPanel(JPanel userProcessContainer, Seller seller, Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.seller = seller;
        this.network=network;
        
        txtBuyer.setText(seller.getName());
        txtPosition.setText(seller.getPosition());
        txtAddress.setText(seller.getAddress());
        txtTelephone.setText(seller.getTelephone());
        txtBuyer.setEnabled(false);
        txtPosition.setEnabled(false);
        txtAddress.setEnabled(false);
        txtTelephone.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtBuyer = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(java.awt.Color.pink);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Seller name:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel7.setText("Position:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));
        add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 184, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 96, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 280, 96, -1));
        add(txtBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 184, -1));

        btnBack.setText("< back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Manage Information Screen");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 21, -1, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 184, -1));

        jLabel8.setText("Address:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));
        add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 184, -1));

        jLabel9.setText("Telephone:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/005-门店.png"))); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/场景2.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtBuyer.setEnabled(true);
        txtPosition.setEnabled(true);
        txtAddress.setEnabled(true);
        txtTelephone.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        seller.setName(txtBuyer.getText());
        seller.setPosition(txtPosition.getText());
        seller.setAddress(txtAddress.getText());
        seller.setTelephone(txtTelephone.getText());
        
        txtBuyer.setEnabled(false);
        txtPosition.setEnabled(false);
        txtAddress.setEnabled(false);
        txtTelephone.setEnabled(false);
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBuyer;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
