/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DeliveryCompany.DeliveryMan;

import Business.BuyerOrder.BuyOrderItem;
import Business.ExpressCompany.Deliveryman;
import Business.ExpressCompany.ExpressCompany;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Interface.DeliveryCompany.DeliveryMan.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TT1
 */
public class ConfirmDeliveryOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmDeliveryOrderJPanel
     */
    JPanel userProcessContainer;
   UserAccount account;
   Network network;
   Deliveryman deliveryman;

    public ConfirmDeliveryOrderJPanel(JPanel userProcessContainer, UserAccount account, Network network) {
       initComponents();
        this.network=network;
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        
        for(ExpressCompany c:network.getExpressCompanyDir().getExpressCompanyList()){
            for(Deliveryman d:c.getDeliverymanDirectory().getDeliverymanList()){
                if(d.getUserAccount().getUsername().equals(account.getUsername()))
                    deliveryman=d;
            }
        }
            
        
        populateTable();
        labelStatus();
        
        jComboBox1.addItem("WORK");
        jComboBox1.addItem("REST");
        jComboBox1.addItem("BUSY");
    }
 public void populateTable(){
        int rowCount = jTable1.getRowCount();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        for(BuyOrderItem buyOrderItem:deliveryman.getBuyOrder().getOrderItemList()){
            
                Object row[] = new Object[6];
                row[0] = buyOrderItem;
                row[1] =buyOrderItem.getQuantity();
               
                row[2] =buyOrderItem.getBuyer().getPosition();
               
                row[3]=buyOrderItem.getGood().getSeller().getPosition();
                row[4]=buyOrderItem.getStatus();
                row[5]=buyOrderItem.getCreateTime();
                
                        
                
                model.addRow(row);
                }
            }
 public void labelStatus(){
     jStatus.setText(deliveryman.getStatus());
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        btnRefuse = new javax.swing.JButton();
        jStatus = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnView = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(java.awt.Color.pink);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("DeliveryMan Workarea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 23, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Goods", "Quantity", "Buyer Position", "Seller Position", "Status", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(8);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 112, 806, 147));

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 420, 160, -1));

        btnRefuse.setText("Refuse");
        btnRefuse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefuseActionPerformed(evt);
            }
        });
        add(btnRefuse, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 460, 160, -1));

        jStatus.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jStatus.setText("\"status\"");
        add(jStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 285, -1, -1));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 334, 92, -1));

        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 420, 160, -1));

        btnFinish.setText("Finish");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });
        add(btnFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 460, 160, -1));

        btnChange.setText("Change my status");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 333, 160, -1));

        jLabel4.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel4.setText("My status:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 285, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/012-服务.png"))); // NOI18N
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 70, 70));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/014-快递员.png"))); // NOI18N
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 70, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
            
            
            
           String status = (String)jComboBox1.getSelectedItem();
           deliveryman.setStatus(status);
           
         JOptionPane.showMessageDialog(null, "Change Your Status to "+status+" Successfully");
         labelStatus();

    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
      
        BuyOrderItem buyOrderItem = (BuyOrderItem)jTable1.getValueAt(selectedRow, 0);
        
        if(buyOrderItem.getStatus().equals("ASSIGND Deliveryman")){
            buyOrderItem.setStatus("Deliveryman Deliverying");
            JOptionPane.showMessageDialog(null, "Assigned this order Successfully");
        }
            else
            JOptionPane.showMessageDialog(null, "You can't handle this order", "Warning",JOptionPane.WARNING_MESSAGE);
         populateTable();
            
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
      
        BuyOrderItem buyOrderItem = (BuyOrderItem)jTable1.getValueAt(selectedRow, 0);
         CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add(new DeliveryViewBuyOrderJPanel(userProcessContainer,buyOrderItem));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnRefuseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefuseActionPerformed
        // TODO add your handling code here:
          int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
      
        BuyOrderItem buyOrderItem = (BuyOrderItem)jTable1.getValueAt(selectedRow, 0);
        
        if(buyOrderItem.getStatus().equals("ASSIGND Deliveryman")){
            buyOrderItem.setStatus("Deliveryman Refused");
            deliveryman.getBuyOrder().getOrderItemList().remove(buyOrderItem);
            JOptionPane.showMessageDialog(null, "Refused this order Successfully");
        }
            else
            JOptionPane.showMessageDialog(null, "You can't handle this order", "Warning",JOptionPane.WARNING_MESSAGE);
         populateTable();
            
    }//GEN-LAST:event_btnRefuseActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
      
        BuyOrderItem buyOrderItem = (BuyOrderItem)jTable1.getValueAt(selectedRow, 0);
        
        if(buyOrderItem.getStatus().equals("Deliveryman Deliverying")){
            buyOrderItem.setStatus("DELIVERED");
            JOptionPane.showMessageDialog(null, "Finished this order Successfully");
        }
            else
            JOptionPane.showMessageDialog(null, "You can't handle this order", "Warning",JOptionPane.WARNING_MESSAGE);
         populateTable();
            
    }//GEN-LAST:event_btnFinishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnRefuse;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jStatus;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
