/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Buyer;

import Business.Buyer.Buyer;
import Business.EcoSystem;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author TT1
 */
public class BuyerMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BuyerMainJPanel
     */
    JPanel userProcessContainer; 
    UserAccount account;
    Network network;
    

    public BuyerMainJPanel(JPanel userProcessContainer, UserAccount account, Network network) {
         initComponents();
         this.userProcessContainer=userProcessContainer;
         this.account=account;
         this.network=network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnshopping = new javax.swing.JButton();
        btnHistoryOrder = new javax.swing.JButton();
        btnManageInformation = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(java.awt.Color.pink);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Buyer Main Screen");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 42, -1, -1));

        btnshopping.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnshopping.setText("Shopping");
        btnshopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshoppingActionPerformed(evt);
            }
        });
        add(btnshopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 228, 41));

        btnHistoryOrder.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnHistoryOrder.setText("History order");
        btnHistoryOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryOrderActionPerformed(evt);
            }
        });
        add(btnHistoryOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 228, 41));

        btnManageInformation.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnManageInformation.setText("Manage information");
        btnManageInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageInformationActionPerformed(evt);
            }
        });
        add(btnManageInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 228, 41));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/电商插画 (2).png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/购物 (1).png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 31, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnshoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshoppingActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add(new ShoppingJPanel(userProcessContainer,account,network));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnshoppingActionPerformed

    private void btnHistoryOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryOrderActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add(new BuyerHistoryOrderJPanel(userProcessContainer,account,network));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnHistoryOrderActionPerformed

    private void btnManageInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageInformationActionPerformed
        // TODO add your handling code here:
        Buyer b = new Buyer();
        for(Buyer buyer: network.getBuyerDirectory().getBuyerList()){
            if(buyer.getUserAccount().equals(account)){
                b = buyer;
            }
        }
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add(new ManageBuyerInformationJPanel(userProcessContainer,b,network));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageInformationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistoryOrder;
    private javax.swing.JButton btnManageInformation;
    private javax.swing.JButton btnshopping;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
