/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Buyer;

import Business.BuyerOrder.BuyOrderItem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author TT1
 */
public class ConnectServiceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConnectServiceJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    BuyOrderItem item;
    public ConnectServiceJPanel(JPanel userProcessContainer, UserAccount account,BuyOrderItem item) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.item = item;
        
        populateChatRecord();
    }
    
    public void populateChatRecord(){
        String chatRecord = "";
        for(int i=0;i<item.getMessages().size();i++){
             chatRecord=chatRecord +item.getMessages().get(i)+"\r\n";
        }
           
           
        
        txtChatRecord.setLineWrap(true);
        txtChatRecord.setWrapStyleWord(true);
        txtChatRecord.setText(chatRecord);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChatRecord = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChatBox = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(java.awt.Color.pink);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("< back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 483, -1, -1));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Connect Service Screen");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 45, -1, -1));

        jLabel2.setText("Chat Record:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 150, -1, -1));

        txtChatRecord.setColumns(20);
        txtChatRecord.setRows(5);
        txtChatRecord.setEnabled(false);
        jScrollPane1.setViewportView(txtChatRecord);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 150, 449, 187));

        jLabel3.setText("Chat Box:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 373, -1, -1));

        txtChatBox.setColumns(20);
        txtChatBox.setRows(5);
        jScrollPane2.setViewportView(txtChatBox);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 373, 326, -1));

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 396, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/客服 (1).png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 120, 100));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/问号1.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 120, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        String word = txtChatBox.getText();
        Date time = new Date();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        String message = format.format(time) + " : " +account.getUsername() + " : " + word;
        item.getMessages().add(message);
        txtChatBox.setText("");
        populateChatRecord();
    }//GEN-LAST:event_btnSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtChatBox;
    private javax.swing.JTextArea txtChatRecord;
    // End of variables declaration//GEN-END:variables
}
