/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Buyer;

import Business.BuyerOrder.BuyOrderItem;
import Business.Goods.Comment;
import Business.Goods.Good;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TT1
 */
public class ViewDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDetailsJPanel
     */
    JPanel userProcessContainer;
    Good good;
    public ViewDetailsJPanel(JPanel userProcessContainer,Good good) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.good = good;
        txtGood.setText(good.getProdName());
        txtPrice.setText(String.valueOf(good.getPrice()));
        txtSeller.setText(good.getSeller().getName());
        txtPosition.setText(good.getSeller().getPosition());
        txtInventory.setText(String.valueOf(good.getQuantity()));
        
        int rowCount = commentTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)commentTable.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Comment comment: good.getComments().getCommentList()){
            Object row[] = new Object[4];
            row[0] = comment.getBuyer();
            row[1] = comment.getScore();
            row[2] = comment.getDate();
            row[3] = comment.getWord();

            model.addRow(row);
        }  
        
        if(good.getImagePath()!=null){
//            ImageIcon photo = new ImageIcon(good.getImagePath());
//            Image image = photo.getImage();
//            image = image.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
//            lblImage.setIcon(new ImageIcon(image));
    Image im=Toolkit.getDefaultToolkit().createImage(good.getImagePath());// Returns an image which gets pixel data from the specified file.
        im=im.getScaledInstance(200, 200, Image.SCALE_SMOOTH);//Creates a scaled version of this image.
        ImageIcon ii=new ImageIcon(im);//Creates an uninitialized image icon.
        lblImage.setIcon(ii);
        }
        else{
            lblImage.setText("No picture!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSeller = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGood = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtInventory = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        commentTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(java.awt.Color.pink);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSeller.setEnabled(false);
        add(txtSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 192, 139, -1));

        jLabel6.setText("Seller:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 197, -1, -1));

        jLabel4.setText("Good:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 109, -1, -1));

        txtGood.setEnabled(false);
        add(txtGood, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 104, 139, -1));

        txtPrice.setEnabled(false);
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 148, 139, -1));

        jLabel5.setText("Price:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 153, -1, -1));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Details Information Screen");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 31, 366, -1));

        btnBack.setText("< back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, -1, -1));

        jLabel7.setText("Position:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 241, -1, -1));

        txtPosition.setEnabled(false);
        add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 236, 142, -1));

        jLabel8.setText("Inventory:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 285, -1, -1));

        txtInventory.setEnabled(false);
        add(txtInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 280, 142, -1));

        jLabel2.setText("Comments:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel9.setText("Image:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 117, -1, -1));

        lblImage.setText("jLabel3");
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 116, 166, 190));

        commentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Buyer", "Score", "Date", "Comment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(commentTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 758, 138));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/商品.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/电商服务.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTable commentTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField txtGood;
    private javax.swing.JTextField txtInventory;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSeller;
    // End of variables declaration//GEN-END:variables
}
