/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DeliveryCompany;

import Business.EcoSystem;
import Business.ExpressCompany.ExpressCompany;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author jiaohongmei
 */
public class DeliveryCompanyMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryCompanyMainJPanel
     */
   JPanel userProcessContainer;
   UserAccount account;
   Network network;
   ExpressCompany expressCompany;
   EcoSystem system;

    public DeliveryCompanyMainJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system,Network network) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
        this.network=network;
        this.account=account;
        this.system=system;
        for(ExpressCompany e:network.getExpressCompanyDir().getExpressCompanyList()){
            if(e.getUserAccount().equals(account))
                expressCompany=e;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAssign = new javax.swing.JButton();
        btnManageDriver = new javax.swing.JButton();
        btnDeliveryman = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(java.awt.Color.pink);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Express Company Main Screen");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        btnAssign.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnAssign.setText("Assign Order");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 378, 41));

        btnManageDriver.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnManageDriver.setText("Manage Driver");
        btnManageDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDriverActionPerformed(evt);
            }
        });
        add(btnManageDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 378, 41));

        btnDeliveryman.setFont(new java.awt.Font("宋体", 2, 18)); // NOI18N
        btnDeliveryman.setText("Manage Deliveryman");
        btnDeliveryman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliverymanActionPerformed(evt);
            }
        });
        add(btnDeliveryman, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 378, 41));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/电商插画 (3).png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/014-物流.png"))); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 70, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add(new ManageExpressOrderJPanel(userProcessContainer,expressCompany,network));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnManageDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDriverActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add(new ManageDriverJPanel(userProcessContainer,expressCompany,system,network));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDriverActionPerformed

    private void btnDeliverymanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliverymanActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add(new ManageDeliveryManJPanel(userProcessContainer,expressCompany,system,network));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDeliverymanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnDeliveryman;
    private javax.swing.JButton btnManageDriver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    // End of variables declaration//GEN-END:variables
}
