/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DeliveryCompany;

import Business.EcoSystem;
import Business.ExpressCompany.Driver;
import Business.ExpressCompany.ExpressCompany;
import Business.Network.Network;
import Business.Role.DriverRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TT1
 */
public class ManageDriverJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDriverJPanel
     */
   JPanel userProcessContainer;
   ExpressCompany expressCompany;
    EcoSystem system;
    Network network;
    String oldname = "";

    ManageDriverJPanel(JPanel userProcessContainer, ExpressCompany expressCompany, EcoSystem system, Network network) {
        initComponents();
        this.network=network;
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.expressCompany=expressCompany;
        btnSave.setEnabled(false);
        txtPosition.setEnabled(false);
      txtUsername.setEnabled(false);
      txtPassword.setEnabled(false);
      txtTelephone.setEnabled(false);
        populateTable();
    }
     public void populateTable(){
        int rowCount = jTable1.getRowCount();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        for(Driver deliveryman:expressCompany.getDriverDir().getDriverList()){
            
                Object row[] = new Object[5];
                row[0] = deliveryman;
                row[1] =deliveryman.getUserAccount().getUsername();
                row[2] =deliveryman.getUserAccount().getPassword();
                row[3] =deliveryman.getTelephone();
                row[4]=deliveryman.getStatus();
                        
                
                model.addRow(row);
                }
            }

     private boolean usernamePatternCorrect(String username) {
    //Pattern p = Pattern.compile("^[a-zA-Z0-9]+_[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        Pattern p = Pattern.compile("^[a-zA-Z0-9]+_[a-zA-Z0-9]+$");
        Matcher m = p.matcher(username);
        boolean b = m.matches();
        return b;

    }

    private boolean passwordPatternCorrect(String password) {
        Pattern p = Pattern.compile("^(?![A-Za-z0-9]+$)(?![a-z0-9\\W]+$)(?![A-Za-z\\W]+$)(?![A-Z0-9\\W]+$)[a-zA-Z0-9\\W]{6,}$");
        Matcher m = p.matcher(password);
        boolean b = m.matches();
        return b;

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPassword1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTelephone1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnFreshTable = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUsername1 = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPosition1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setBackground(java.awt.Color.pink);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassword1KeyReleased(evt);
            }
        });
        add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 586, 134, 27));

        jLabel4.setText("Position:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 385, -1, -1));

        jLabel7.setText("Telephone:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 438, -1, -1));

        jLabel10.setText("Password:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 591, -1, -1));

        jLabel11.setText("Telephone:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 591, -1, -1));
        add(txtTelephone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 586, 166, 27));

        jLabel5.setText("Username:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 385, -1, -1));

        btnSave.setText("Save");
        btnSave.setMaximumSize(new java.awt.Dimension(100, 30));
        btnSave.setMinimumSize(new java.awt.Dimension(100, 30));
        btnSave.setPreferredSize(new java.awt.Dimension(100, 30));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, -1, -1));

        jLabel12.setText("Position:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 542, -1, -1));

        jLabel13.setText("Username:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 542, -1, -1));

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 433, 134, 27));

        btnCreate.setText("Create");
        btnCreate.setMaximumSize(new java.awt.Dimension(100, 30));
        btnCreate.setMinimumSize(new java.awt.Dimension(100, 30));
        btnCreate.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, -1, -1));

        jLabel6.setText("Password:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 438, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Position", "Username", "Password", "Telephone", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 115, 770, 147));

        btnBack.setText("< back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 638, -1, -1));

        jLabel3.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel3.setText("Delete Driver:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 288, -1, -1));

        btnFreshTable.setText("Fresh table");
        add(btnFreshTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel8.setText("Update Driver:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 339, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.setMaximumSize(new java.awt.Dimension(100, 30));
        btnDelete.setMinimumSize(new java.awt.Dimension(100, 30));
        btnDelete.setPreferredSize(new java.awt.Dimension(100, 30));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.setMaximumSize(new java.awt.Dimension(100, 30));
        btnUpdate.setMinimumSize(new java.awt.Dimension(100, 30));
        btnUpdate.setPreferredSize(new java.awt.Dimension(100, 30));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, -1, -1));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Manage Driver");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 21, -1, -1));

        jLabel2.setText("Driver list:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 87, -1, -1));
        add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 433, 166, 27));

        jLabel9.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel9.setText("Create new Driver:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 497, -1, -1));

        txtUsername1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsername1KeyReleased(evt);
            }
        });
        add(txtUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 537, 169, 27));
        add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 380, 134, 27));

        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 380, 169, 27));
        add(txtPosition1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 537, 134, 27));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/015-运输.png"))); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 70, 70));
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 80, 20));
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 80, 20));
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 80, 20));
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 80, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
     Driver deliveryman = (Driver)jTable1.getValueAt(selectedRow, 0);
      expressCompany.getDriverDir().getDriverList().remove(deliveryman);
      
       
       UserAccount us=new UserAccount();
       us=deliveryman.getUserAccount();
       system.getUserAccountDirectory().getUserAccountList().remove(us);
          populateTable();
         JOptionPane.showMessageDialog(null, "Delete the driver successfully!");   
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
       Driver deliveryman = (Driver)jTable1.getValueAt(selectedRow, 0);
      txtPosition.setText(deliveryman.getPosition());
      txtUsername.setText(deliveryman.getUserAccount().getUsername());
      txtPassword.setText(deliveryman.getUserAccount().getPassword());
      txtTelephone.setText(deliveryman.getTelephone());
      oldname = deliveryman.getUserAccount().getUsername();
      
       btnSave.setEnabled(true);
       btnUpdate.setEnabled(false);
       txtPosition.setEnabled(true);
      txtUsername.setEnabled(true);
      txtPassword.setEnabled(true);
      txtTelephone.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
      Driver deliveryman = (Driver)jTable1.getValueAt(selectedRow, 0);
      
     //check If Username Is Unique
        if(txtUsername.getText().equals(oldname)){}
        else{
            if(system.getUserAccountDirectory().checkIfUsernameIsUnique(txtUsername.getText())){}
            else{
                JOptionPane.showMessageDialog(null, "This username has existed!", "Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        oldname = "";
        
        //check format of username and password
        if (usernamePatternCorrect(txtUsername.getText()) == false || passwordPatternCorrect(txtPassword.getText()) == false)
        {
         txtUsername.setBorder(BorderFactory.createLineBorder(Color.red));
         txtPassword.setBorder(BorderFactory.createLineBorder(Color.red));
         return;
        } 
        txtUsername.setBorder(BorderFactory.createLineBorder(Color.gray));
        txtPassword.setBorder(BorderFactory.createLineBorder(Color.gray));
      
      deliveryman.setPosition(txtPosition.getText());
      deliveryman.setTelephone(txtTelephone.getText());
      deliveryman.getUserAccount().setPassword(txtPassword.getText());
      deliveryman.getUserAccount().setUsername(txtUsername.getText());
       populateTable();
       
       txtUsername.setText("");
        txtPassword.setText("");
        txtTelephone.setText("");
        txtPosition.setText("");
         populateTable();
        btnSave.setEnabled(false);
       btnUpdate.setEnabled(true);
       txtPosition.setEnabled(false);
      txtUsername.setEnabled(false);
      txtPassword.setEnabled(false);
      txtTelephone.setEnabled(false);
      jLabel15.setText("");
        jLabel16.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
         String username=txtUsername1.getText();
        String password=txtPassword1.getText();
        String Position=txtPosition1.getText();
        String telePhone=txtTelephone1.getText();
        
        if(system.getUserAccountDirectory().checkIfUsernameIsUnique(txtUsername1.getText())){}
        else{
            JOptionPane.showMessageDialog(null, "This username has existed!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //check format of username and password
        if (usernamePatternCorrect(txtUsername1.getText()) == false || passwordPatternCorrect(txtPassword1.getText()) == false)
        {
         txtUsername1.setBorder(BorderFactory.createLineBorder(Color.red));
         txtPassword1.setBorder(BorderFactory.createLineBorder(Color.red));
         return;
        } 
        txtUsername1.setBorder(BorderFactory.createLineBorder(Color.gray));
         txtPassword1.setBorder(BorderFactory.createLineBorder(Color.gray));
        
        Driver deliveryman=new Driver();
        UserAccount userAccount=new UserAccount();
        DriverRole role=new DriverRole();
        
        userAccount=system.getUserAccountDirectory().createUserAccount(username,password,role); 
        deliveryman.setPosition(Position);
        deliveryman.setTelephone(telePhone);
        deliveryman.setStatus("WORK");
        deliveryman.setUserAccount(userAccount);
        network.getUserAccountDirectory().getUserAccountList().add(userAccount);
       
         expressCompany.getDriverDir().getDriverList().add(deliveryman);
        
       
        txtUsername1.setText("");
        txtPassword1.setText("");
        txtTelephone1.setText("");
        txtPosition1.setText("");
         populateTable();
         jLabel17.setText("");
        jLabel18.setText("");
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);  
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        // TODO add your handling code here:
        if(usernamePatternCorrect(txtUsername.getText())==false){
            jLabel15.setText("Invalid Format");
            jLabel15.setForeground(Color.red);
             
        }
        else
        {jLabel15.setText("Correct Format!");
            jLabel15.setForeground(Color.blue);
        }
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        // TODO add your handling code here:
        if(passwordPatternCorrect(txtPassword.getText())==false){
            jLabel16.setText("Invalid Format");
            jLabel16.setForeground(Color.red);

        }
        else
        {jLabel16.setText("Correct Format!");
            jLabel16.setForeground(Color.blue);
        }
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtUsername1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsername1KeyReleased
        // TODO add your handling code here:
        if(usernamePatternCorrect(txtUsername1.getText())==false){
            jLabel17.setText("Invalid Format");
            jLabel17.setForeground(Color.red);
             
        }
        else
        {jLabel17.setText("Correct Format!");
            jLabel17.setForeground(Color.blue);
        }
    }//GEN-LAST:event_txtUsername1KeyReleased

    private void txtPassword1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassword1KeyReleased
        // TODO add your handling code here:
        if(passwordPatternCorrect(txtPassword1.getText())==false){
            jLabel18.setText("Invalid Format");
            jLabel18.setForeground(Color.red);

        }
        else
        {jLabel18.setText("Correct Format!");
            jLabel18.setForeground(Color.blue);
        }
    }//GEN-LAST:event_txtPassword1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFreshTable;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPassword1;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtPosition1;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtTelephone1;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables
}
