/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DeliveryCompany;

import Business.EcoSystem;
import Business.ExpressCompany.Deliveryman;
import Business.ExpressCompany.ExpressCompany;
import Business.Network.Network;
import Business.Role.DeliverymanRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TT1
 */
public class ManageDeliveryManJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDeliveryManJPanel
     */
   JPanel userProcessContainer;
   ExpressCompany expressCompany;
   EcoSystem system;
   Network network;
   String oldname = "";
    ManageDeliveryManJPanel(JPanel userProcessContainer, ExpressCompany expressCompany, EcoSystem system, Network network) {
        initComponents();
        this.network=network;
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.expressCompany=expressCompany;
        btnSave.setEnabled(false);
        txtPosition.setEnabled(false);
      txtUsername.setEnabled(false);
      txtPassword.setEnabled(false);
      txtTelephone.setEnabled(false);
        populateTable();
    }
    public void populateTable(){
        int rowCount = jTable1.getRowCount();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        for(Deliveryman deliveryman:expressCompany.getDeliverymanDirectory().getDeliverymanList()){
            
                Object row[] = new Object[5];
                row[0] = deliveryman;
                row[1] =deliveryman.getUserAccount().getUsername();
                row[2] =deliveryman.getUserAccount().getPassword();
                row[3] =deliveryman.getTelephone();
                row[4]=deliveryman.getStatus();
                        
                
                model.addRow(row);
                }
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPassword1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTelephone1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnFreshTable = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUsername1 = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPosition1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setBackground(java.awt.Color.pink);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 567, 134, -1));

        jLabel4.setText("Position:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 368, -1, -1));

        jLabel7.setText("Telephone:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 420, -1, -1));

        jLabel10.setText("Password:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 572, -1, -1));

        jLabel11.setText("Telephone:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 572, -1, -1));
        add(txtTelephone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 166, -1));

        jLabel5.setText("Username:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 368, -1, -1));

        btnSave.setText("Save");
        btnSave.setMaximumSize(new java.awt.Dimension(100, 30));
        btnSave.setMinimumSize(new java.awt.Dimension(100, 30));
        btnSave.setPreferredSize(new java.awt.Dimension(100, 30));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 100, -1));

        jLabel12.setText("Position:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 524, -1, -1));

        jLabel13.setText("Username:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 524, -1, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 415, 134, -1));

        btnCreate.setText("Create");
        btnCreate.setMaximumSize(new java.awt.Dimension(100, 30));
        btnCreate.setMinimumSize(new java.awt.Dimension(100, 30));
        btnCreate.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, -1, -1));

        jLabel6.setText("Password:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 420, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Position", "Username", "Password", "Telephone", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 808, 147));

        btnBack.setText("< back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, -1));

        jLabel3.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel3.setText("Delete Delivery Man:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        btnFreshTable.setText("Fresh table");
        add(btnFreshTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel8.setText("Update Delivery Man:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 323, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.setMaximumSize(new java.awt.Dimension(100, 30));
        btnDelete.setMinimumSize(new java.awt.Dimension(100, 30));
        btnDelete.setPreferredSize(new java.awt.Dimension(100, 30));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.setMaximumSize(new java.awt.Dimension(100, 30));
        btnUpdate.setMinimumSize(new java.awt.Dimension(100, 30));
        btnUpdate.setPreferredSize(new java.awt.Dimension(100, 30));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, -1, -1));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("Manage Delivery Man");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 21, -1, -1));

        jLabel2.setText("Delivery Man list:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 166, -1));

        jLabel9.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel9.setText("Create new Delivery Man:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 479, -1, -1));
        add(txtUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 519, 169, -1));
        add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 134, -1));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 363, 169, -1));
        add(txtPosition1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 134, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/006-快递员.png"))); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 70, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
 int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
     Deliveryman deliveryman = (Deliveryman)jTable1.getValueAt(selectedRow, 0);
      expressCompany.getDeliverymanDirectory().getDeliverymanList().remove(deliveryman);
      
       
       UserAccount us=new UserAccount();
       us=deliveryman.getUserAccount();
       system.getUserAccountDirectory().getUserAccountList().remove(us);
          populateTable();
         JOptionPane.showMessageDialog(null, "Delete the deliveryman successfully!");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
       Deliveryman deliveryman = (Deliveryman)jTable1.getValueAt(selectedRow, 0);
      txtPosition.setText(deliveryman.getPosition());
      txtUsername.setText(deliveryman.getUserAccount().getUsername());
      txtPassword.setText(deliveryman.getUserAccount().getPassword());
      txtTelephone.setText(deliveryman.getTelephone());
      oldname = deliveryman.getUserAccount().getUsername();
      
       btnSave.setEnabled(true);
       btnUpdate.setEnabled(false);
       txtPosition.setEnabled(true);
      txtUsername.setEnabled(true);
      txtPassword.setEnabled(true);
      txtTelephone.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
       Deliveryman deliveryman = (Deliveryman)jTable1.getValueAt(selectedRow, 0);
      //check If Username Is Unique
        if(txtUsername.getText().equals(oldname)){}
        else{
            if(system.getUserAccountDirectory().checkIfUsernameIsUnique(txtUsername.getText())){}
            else{
                JOptionPane.showMessageDialog(null, "This username has existed!", "Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        oldname = "";
      
      deliveryman.setPosition(txtPosition.getText());
      deliveryman.setTelephone(txtTelephone.getText());
      deliveryman.getUserAccount().setPassword(txtPassword.getText());
      deliveryman.getUserAccount().setUsername(txtUsername.getText());
       populateTable();
       
        btnSave.setEnabled(false);
       btnUpdate.setEnabled(true);
       txtPosition.setEnabled(false);
      txtUsername.setEnabled(false);
      txtPassword.setEnabled(false);
      txtTelephone.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String username=txtUsername1.getText();
        String password=txtPassword1.getText();
        String Position=txtPosition1.getText();
        String telePhone=txtTelephone1.getText();
        
        
        Deliveryman deliveryman=new Deliveryman();
        UserAccount userAccount=new UserAccount();
        DeliverymanRole role=new DeliverymanRole();
        
        userAccount=system.getUserAccountDirectory().createUserAccount(username,password,role); 
        deliveryman.setPosition(Position);
        deliveryman.setTelephone(telePhone);
        deliveryman.setStatus("WORK");
        deliveryman.setUserAccount(userAccount);
       network.getUserAccountDirectory().getUserAccountList().add(userAccount);
         expressCompany.getDeliverymanDirectory().getDeliverymanList().add(deliveryman);
        
       
        txtUsername1.setText("");
        txtPassword1.setText("");
        txtTelephone1.setText("");
        txtPosition1.setText("");
         populateTable();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);  
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFreshTable;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPassword1;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtPosition1;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtTelephone1;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables
}
